### PR TITLE
Upgraded to Spark 3.0 and Pulsar 2.7

### PR DESCRIPTION
**Pull request by Aegeaner**
I have upgraded pulsar-spark to Spark 3.1.0 & Pulsar 2.7.0.
Relative issue: https://github.com/streamnative/pulsar-spark/issues/38

### CODE REVIEW

**Review by jianyun8023 — COMMENTED** [review]
I think these modified codes are fine. Because it's major changes in the API changes brought by the version upgrade.

**Comment by hanguyen6** [comment]
Spark DataSource V2 APIs has been refactored to unify between streaming and batch. Should we upgrade our code to follow the updated abstraction: 

https://issues.apache.org/jira/browse/SPARK-25390

write API refactor:
https://docs.google.com/document/d/1vI26UEuDpVuOjWw4WPoH2T6y8WAekwtI7qoowhOFnI4/edit#

read API refactoring: 
https://docs.google.com/document/d/1uUmKCpWLdh9vHxP7AWJ9EgbwB_U6T3EJYNjhISGmiQg/edit#

I have updated code to follow that abstraction and can help if needed.

**Comment by jiazhai** [comment]
> Spark DataSource V2 APIs has been refactored to unify between streaming and batch. Should we upgrade our code to follow the updated abstraction:
> 
> https://issues.apache.org/jira/browse/SPARK-25390
> 
> write API refactor:
> https://docs.google.com/document/d/1vI26UEuDpVuOjWw4WPoH2T6y8WAekwtI7qoowhOFnI4/edit#
> 
> read API refactoring:
> https://docs.google.com/document/d/1uUmKCpWLdh9vHxP7AWJ9EgbwB_U6T3EJYNjhISGmiQg/edit#
> 
> I have updated code to follow that abstraction and can help if needed.

Thanks @hanguyen6 for the great proposal. It would be great help to have this catchup. I also opened a new issue #43 to track this item.

**Comment by jiazhai** [comment]
@Aegeaner Would you please help check and fix the CI errors?

**Comment by syhily** [comment]
@Aegeaner Thank you for your patience, I would review this PR later today in china.

**Comment by vinothchandar** [comment]
This would be nice to have. The APIs between Spark 2 and Spark 3 are not very compatible. But wondering how or if, this PR maintains support for Spark 2 as well

**Pull request closed without merging**
